spring:
  application:
    name: tech-swipe-api

  profiles:
    active: local

  config:
    import:
      - monitoring.yml
      - storage-mysql.yml

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org.apache.coyote.http11: trace

---
spring:
  config:
    activate:
      on-profile: local-dev

logging:
  level:
    org.apache.coyote.http11: trace

---
spring:
  config:
    activate:
      on-profile: dev

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    org.apache.coyote.http11: trace

---
spring:
  config:
    activate:
      on-profile: prod
