spring:
  application:
    name: batch-app

  profiles:
    active: local

  main.web-application-type: none

  config:
    import:
      - storage-mysql.yml
      - logging.yml
      - aws.yml
      - openai.yml

  batch:
    job:
      enabled: true
      name: ${job.name:healthCheckJob}
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local-dev

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

app:
  alert:
    type: discord
    discord:
      webhook-url: ${DISCORD_WEBHOOK_URL}
