services:
  mysql:
    container_name: mysql
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
        MYSQL_DATABASE: tech_swipe
        TZ: Asia/Seoul
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
        - ./docker/mysql:/var/lib/mysql