spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  flyway:
    enabled: true
    fail-on-missing-locations: true

  sql:
    init:
      mode: never

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/techswipe
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: local-dev

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace

---
spring:
  config:
    activate:
      on-profile: prod