spring:
  application:
    name: tech-swipe-batch

  profiles:
    active: local

  config:
    import:
      - storage-mysql.yml

  batch:
    job:
      enabled: true
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

  ai:
    retry:
      max-attempts: 1
    openai:
      api-key: ${OPENAI_API_KEY:not-used}

app:
  image:
    s3:
      bucket-name: ${AWS_S3_BUCKET}
  collection:
    openai:
      categorization-model: ${OPENAI_CATEGORIZATION_MODEL}

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local-dev

app:
  image:
    s3:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: dev

app:
  image:
    s3:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

app:
  image:
    s3:
      enabled: true
  collection:
    openai:
      enabled: true
