spring:
  application:
    name: tech-swipe-batch

  profiles:
    active: local

  config:
    import:
      - storage-mysql.yml

  batch:
    job:
      enabled: true
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:not-used}
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: local-dev

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

app:
  image:
    s3:
      enabled: true
      bucket-name: ${AWS_S3_BUCKET}
---
spring:
  config:
    activate:
      on-profile: dev

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

app:
  image:
    s3:
      enabled: true
      bucket-name: ${AWS_S3_BUCKET}
---
spring:
  config:
    activate:
      on-profile: prod

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

app:
  image:
    s3:
      enabled: true
      bucket-name: ${AWS_S3_BUCKET}
  collection:
    openai:
      enabled: true
      categorization-model: ${OPENAI_CATEGORIZATION_MODEL}
  client:
    sync:
      base-url: ${TECH_SWIPE_ADMIN_URL}
      authorization: ${TECH_SWIPE_ADMIN_AUTHORIZATION}
