spring:
  application:
    name: tech-swipe-admin-api

  profiles:
    active: local

  config:
    import:
      - storage-mysql.yml

---
spring:
  config:
    activate:
      on-profile: local

  security:
    user:
      name: admin
      password: 1234

logging:
  level:
    org.apache.coyote.http11: trace

---
spring:
  config:
    activate:
      on-profile: local-dev

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

logging:
  level:
    org.apache.coyote.http11: trace

app:
  image:
    s3:
      enabled: true
      bucket-name: ${AWS_S3_BUCKET}

---
spring:
  config:
    activate:
      on-profile: dev

  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

logging:
  level:
    org.apache.coyote.http11: trace

app:
  image:
    s3:
      enabled: true
      bucket-name: ${AWS_S3_BUCKET}

---
spring:
  config:
    activate:
      on-profile: prod

  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

app:
  image:
    s3:
      enabled: true
      bucket-name: ${AWS_S3_BUCKET}
