spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}


app:
  collection:
    openai:
      enabled: true
      api-key: ${OPENAI_API_KEY}
      categorization-model: ${OPENAI_CATEGORIZATION_MODEL}
