spring:
  application:
    name: batch-app

  profiles:
    active: local

  config:
    import:
      - core-db.yml
      - logging.yml

  batch:
    job:
      enabled: true
      name: ${job.name:healthCheckJob}
    jdbc:
      initialize-schema: never
      isolation-level-for-create: default

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile:
        - local-dev
        - dev
        - prod

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o-mini

app.collection.openai:
  enabled: true
  categorization-model: ${OPENAI_CATEGORIZATION_MODEL}

