= 북마크
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[create-group]]
== 북마크 그룹 생성

operation::bookmark/create-group[snippets='http-request,request-headers,request-fields,http-response']


[[group-delete]]
== 북마크 그룹 삭제

operation::bookmark/group-delete[snippets='http-request,request-headers,path-parameters,http-response']


[[groups]]
== 북마크 그룹 목록 조회

operation::bookmark/groups[snippets='http-request,request-headers,http-response,response-fields']


[[get-groups-with-contains]]
== 북마크 그룹 목록 조회(컨텐츠 북마크 여부 포함)

operation::bookmark/get-groups-with-contains[snippets='http-request,request-headers,query-parameters,http-response,response-fields']


[[update-group]]

[[create]]
== 북마크 생성

operation::bookmark/create[snippets='http-request,request-headers,request-fields,http-response']

[[list-query]]
== 북마크 목록 조회

operation::bookmark/list-query[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

[[delete]]
== 북마크 삭제

operation::bookmark/delete[snippets='http-request,request-headers,path-parameters,http-response']

