= 컨텐츠
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


[[get-content-swipe-list]]
== 컨텐츠 스와이프 조회

operation::content/get-content-swipe-list[snippets='http-request,query-parameters,http-response,response-fields']


[[get-content-list-v1]]
== 컨텐츠 리스트 조회 v1

operation::content/get-content-list[snippets='http-request,query-parameters,http-response,response-fields']

[[get-content-list-v2]]
== 컨텐츠 리스트 조회 v2

operation::content/get-content-list-v2[snippets='http-request,query-parameters,http-response,response-fields']

[[get-content-detail]]
== 컨텐츠 상세 조회

operation::content/get-content-detail[snippets='http-request,path-parameters,http-response,response-fields']

[[get-content-count]]
== 컨텐츠 개수 조회

operation::content/get-content-count[snippets='http-request,http-response']

[[content-link]]
== 컨텐츠 링크

컨텐츠의 실제 위치로 이동합니다.

컨텐츠 조회시 컨텐츠의 url 을 아래와 같이 만들어야 합니다.

호스트는 컨텐츠를 조회한 서버와 같습니다.

operation::content/content-link[snippets='http-request,path-parameters,http-response']


[[user-category-get]]
== 사용자 카테고리 조회

operation::content/user-category-get[snippets='http-request,request-headers,http-response,response-fields']

[[user-category-save]]
== 사용자 카테고리 저장

operation::content/user-category-save[snippets='http-request,request-headers,request-fields,http-response']