spring:
  application:
    name: tech-swipe-admin-api

  profiles:
    active: local

  config:
    import:
      - storage-mysql.yml

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org.apache.coyote.http11: debug
---
spring:
  config:
    activate:
      on-profile: local-dev

logging:
  level:
    org.apache.coyote.http11: debug

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.apache.coyote.http11: debug

---
spring:
  config:
    activate:
      on-profile: prod
