spring:
  config.activate.on-profile:
    - local

app:
  image:
    s3:
      enabled: false

---
spring:
  config.activate.on-profile:
    - local-dev
    - dev
    - prod

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

app:
  image:
    s3:
      enabled: true
      bucket-name: ${AWS_S3_BUCKET}
