name: Pull Request Test

on: pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Test with Gradle
      run: ./gradlew --info test
