spring:
  application:
    name: tech-swipe-admin

  profiles:
    active: local
    group:
      local: rds
      dev: rds
      prod: rds

---
spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    org:
      apache.coyote.http11: debug
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      apache.coyote.http11: debug

---
spring:
  config:
    activate:
      on-profile: prod
