spring.config.activate.on-profile:
  - local
  - local-dev

---
spring.config.activate.on-profile:
  - dev
  - prod

app.jwt:
  access-token:
    secret: ${JWT_ACCESS_TOKEN_SECRET}
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token:
    secret: ${JWT_REFRESH_TOKEN_SECRET}
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
